ci:
  skip: [pylint]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.1"
    hooks:
      - id: ruff
        exclude: tests/fixture
        args: ["--fix", "--select", "F,E,W,I"]
  - repo: https://github.com/Pierre-Sassoulas/django-debug-false-checker/
    rev: v0.0.4
    hooks:
      - id: django-debug-false-checker
        exclude: tests/
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: tests/fixture
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        exclude: tests/fixture
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        exclude: tests/fixture
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: tests
        args: ["-sn", "-rn", "--disable=C0111,C0103"]
        types: [python]
