ci:
  skip: [pylint]

repos:
  - repo: https://github.com/Pierre-Sassoulas/django-debug-false-checker/
    rev: v0.0.4
    hooks:
      - id: django-debug-false-checker
        exclude: tests/
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: tests/fixtures/strange_formatting/settings.py
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: tests/fixture
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: tests/fixture
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: tests
        args: ["-sn", "-rn", "--disable=C0111,C0103"]
        types: [python]
